version: '3.7'

services:
  keycloak:
    image: jboss/keycloak:7.0.0
    environment:
      - KEYCLOAK_USER=keycloak
      - KEYCLOAK_PASSWORD=password
    ports:
      - 8080:8080
    network_mode: "host"
  example:
    build:
      context: keycloak-nodejs-connect
      dockerfile: ../Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - keycloak
    network_mode: "host"
